name: Build and Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android build tools
      run: |
        echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "build-tools;30.0.3"
        echo "Installed build tools at /usr/local/lib/android/sdk/build-tools/30.0.3"

    - name: Set up environment variables
      run: |
        echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "Set JAVA_HOME to ${JAVA_HOME}"
        echo "Set ANDROID_HOME to ${ANDROID_HOME}"

    - name: Install apkc
      run: |
        wget https://github.com/ajinasokan/apkc/releases/download/v0.4.1/apkc_0.4.1_linux_amd64.tar.gz
        tar -xzf apkc_0.4.1_linux_amd64.tar.gz
        sudo mv apkc /usr/local/bin/

    - name: Verify paths
      run: apkc doctor

    - name: Create new project
      run: |
        echo -e "com.myapp\nMy App\n" | apkc create myapp

    - name: Generate Keystore
      run: |
        keytool -genkey -v -keystore my-release-key.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000 -storepass password -keypass password -dname "CN=, OU=, O=, L=, S=, C="

    - name: Build APK
      run: |
        cd myapp && apkc build --keystore "./my-release-key.keystore" --storepass "password" --keyalias "alias_name"

    - name: Upload APK to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.repository.upload_url }}
        asset_path: ./myapp/build/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
