name: Build and Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        components: build-tools;33.0.2

    - name: Verify and Prepare APKC
      working-directory: ${{ github.workspace }}
      run: |
        chmod +x ./tools/apkc
        echo "./tools" >> $GITHUB_PATH
        cd tools 
        apkc doctor

    - name: Generate Keystore  
      run: keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

    - name: Build APK
      working-directory: ${{ github.workspace }}/src 
      run: ../tools/apkc build --keystore "../debug.keystore" --storepass "android" --keyalias "androiddebugkey"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.run_id }}

    - name: Upload APK to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/src/build/app-release.apk  
        asset_name: app-release-${{ github.run_id }}.apk
        asset_content_type: application/vnd.android.package-archive
